### PR TITLE
Fixes: Storage GET requests are rejected by AWS CloudFront 

### LINKED ISSUE #34: Storage GET requests are rejected by AWS CloudFront
Background: We have supabase storage running on AWS. All requests are fronted by CloudFront.

When I make a request to get a bucket:
```dart
    final getResponse = await supabaseClient.storage.getBucket(bucketName);
```

CloudFront rejects the request with HTTP 403. It turns out it's because this is a GET request and the Storage API is issuing the request with a body of "{}" (text-plain).  CloudFront does not allow a body on GET requests. These lines appear to be problematic:

https://github.com/supabase-community/storage-dart/blob/main/lib/src/fetch.dart#L56
https://github.com/supabase-community/storage-dart/blob/main/lib/src/fetch.dart#L152

GET requests shouldn't have bodies anyway.

I will try to raise a PR to fix this issue.

### PR DESCRIPTION
**Pull request by dsyrstad**
Fixes #34

### CODE REVIEW

**Comment by bdlukaa** [comment]
Nice catch!

js reference: https://github.com/supabase/storage-js/blob/d6a6b4af2eb1a07bfb64604f9a3317c1576d6dc3/src/lib/fetch.ts#L31-L46

**Review by bdlukaa — APPROVED** [review]
@dshukertjr

**Review by dshukertjr — APPROVED** [review]
@dsyrstad Very nice one! Thanks for the amazing catch!

**Comment by dshukertjr** [comment]
@dsyrstad BTW, if this is your first contribution to Supabase and you haven't received any Supabase t-shirts, you can send me a DM on twitter and I will send you some codes to get free Supabase t-shirts to show our appreciation!
https://twitter.com/dshukertjr

**Comment by dsyrstad** [comment]
@dshukertjr @bdlukaa You're welcome! 

Is there any talk about keeping the Supabase Dart/Flutter versions in sync? Like keeping https://pub.dev/packages/supabase update to date with the auth, storage, postgrest, etc. clients, and also https://pub.dev/packages/supabase_flutter's dependency on the supabase meta package. For example, right now supabase_flutter depends on supabase 0.3.4+1, but supabase is currently at 0.3.6.  Both were published 8 or 9 days ago.

There also seem to be a lot of API changes on the main branch of this repo which are breaking, and not published yet.

Thanks @dshukertjr for the t-shirt offer - I'll hit you up!

**Comment by dshukertjr** [comment]
@dsyrstad That is a great point! I need to do a better job of releasing the latest packages more often. Though as long as the sub packages are being released, developers should be able to use them without updating the `supabase-flutter` version I think. https://dart.dev/tools/pub/dependencies Deleting the `pubspec.lock` file and re-running pub get should update the packages to the latest ones, I think.

**Comment by dsyrstad** [comment]
@dshukertjr I think you're right about packages not being locked in to minor versions as long as the package doesn't commit `pubspec.lock`. But, it depends on your `pubspec.yaml` version spec - if you don't specify `^` in front of the version, it will be hard-locked to that specific version. I don't believe this is the cases for any of the supabase packages.

**Pull request merged**
